# Introduction

This book is a side-by-side comparison of [Polars](https://www.pola.rs/)
and [Pandas](https://pandas.pydata.org/) dataframe libraries,
based on the series [Modern Pandas](https://tomaugspurger.github.io/posts/modern-8-scaling/) by Tom Augsburger.

It provides structured examples of idiomatic Polars and Pandas code, with commentary on the API and performance of both.

For the most part, this book argues that Polars is "better" than Pandas, though I do try and make it clear when Polars is lacking a Pandas feature or otherwise disappoints us.

## Who is this for?

This is for people who already have some familiarity with Pandas, though you don't need to know Polars to read it.
This book is also for people who know Polars but not Pandas, if such a person exists.

## Why write this book?

There's this weird phenomenon where people write data programming code as if they hate themselves.
A lot of clever folks keep doing [really dumb stuff](https://www.aidancooper.co.uk/pandas-anti-patterns/)
with Pandas, and at some point you have to wonder if the Pandas API is too difficult for people.

I *think* Polars is more intuitive and makes it easier to do the right thing. It's also much faster than Pandas at most things, even when you do Pandas the right way.

Hopefully this book shows you how and why to prefer Polars over Pandas.

## Credit

The Pandas examples are mostly lifted from Tom's articles, with some updates for data that's no longer available, and some
code changes to reflect how Pandas is written in 2022. This isn't just me being lazy - I want to draw on Pandas examples that
quite a lot of people are already familiar with.

So credit goes to Tom for the Pandas examples and for the general structure of the articles.

Meanwhile the text content and the Polars examples in this book are all from me.


::: {.panel-tabset}
## Polars

``` {python}
import polars as pl
pl.DataFrame({"col1": [1,2,3], "col2": [2,3,4]})
```

## Pandas

``` {python}
import pandas as pd
pd.DataFrame({"col1": [1,2,3], "col2": [2,3,4]})
```

:::

```{python}
#| tbl-cap: A dataframe

import pandas as pd
import polars as pl
df_pd = pd.DataFrame({"a": [1,2,3], "b": [2,3,4]})
# pl.DataFrame({"col1": [1,2,3], "col2": [2,3,4]})
df_pd
```